import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "material-icons/iconfont/material-icons.css";
import QueryProvider from "../components/module/QueryProvider/QueryProvider";
import "react-toastify/dist/ReactToastify.css";
import { ToastComponent } from "../components/core/ToastComponent/ToastComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <div>
            <ToastComponent />
            {children}
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}
